### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by samzl1** [tkhdyanagi/testinterference#1]
Hi Authors,

Thanks for building up the package. I'm trying to install it and give it a try but find the following error:
<img width="626" alt="Screenshot 2023-08-09 at 4 46 55 PM" src="https://github.com/tkhdyanagi/testinterference/assets/43323075/8c0108ec-3626-44cb-b64b-b413d9cba56f">

Any idea how to solve it?

Best,
Liang

**Comment by tkhdyanagi** [comment]
Dear Liang, 

Thank you for your interest in our package.

I have now verified that the installation is successful without any error on two Windows machines. So this issue might be specific to your environment. 

![20230809184020](https://github.com/tkhdyanagi/testinterference/assets/33080757/e911a2b4-31ae-4c4e-9e5a-915e34112c50)

The error message seems to come from the igraph package (https://cran.r-project.org/web/packages/igraph/index.html). Could you please first remove and reinstall the igraph package, and then check if the installation of the igraph and testinterference packages is successful?

Best,
Takahide

> Hi Authors,
> 
> Thanks for building up the package. I'm trying to install it and give it a try but find the following error: <img alt="Screenshot 2023-08-09 at 4 46 55 PM" width="626" src="https://user-images.githubusercontent.com/43323075/259351010-8c0108ec-3626-44cb-b64b-b413d9cba56f.png">
> 
> Any idea how to solve it?
> 
> Best, Liang

**Comment by tkhdyanagi** [comment]
I have also verified that the installation works successfully on macOS.

![20230809190947](https://github.com/tkhdyanagi/testinterference/assets/33080757/78302d52-8019-4cbb-83ce-f0e3944692e5)

**Comment by szhorvat** [comment]
`greedy_vertex_coloring()` was added in igraph 1.3.0. Do make sure that your igraph version is not older than this.

**Comment by tkhdyanagi** [comment]
Thanks for the helpful information!

> `greedy_vertex_coloring()` was added in igraph 1.3.0. Do make sure that your igraph version is not older than this.

**Comment by samzl1** [comment]
Thanks for all the comments! I just successfully redownloaded my "igraph" package, and now it works!
